package com.lsm.barrister2c.data.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lsm.barrister2c.data.db.PushMessage;
import com.lsm.barrister2c.data.db.Favorite;

import com.lsm.barrister2c.data.db.PushMessageDao;
import com.lsm.barrister2c.data.db.FavoriteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pushMessageDaoConfig;
    private final DaoConfig favoriteDaoConfig;

    private final PushMessageDao pushMessageDao;
    private final FavoriteDao favoriteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pushMessageDaoConfig = daoConfigMap.get(PushMessageDao.class).clone();
        pushMessageDaoConfig.initIdentityScope(type);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        pushMessageDao = new PushMessageDao(pushMessageDaoConfig, this);
        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);

        registerDao(PushMessage.class, pushMessageDao);
        registerDao(Favorite.class, favoriteDao);
    }
    
    public void clear() {
        pushMessageDaoConfig.getIdentityScope().clear();
        favoriteDaoConfig.getIdentityScope().clear();
    }

    public PushMessageDao getPushMessageDao() {
        return pushMessageDao;
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

}
