package com.lsm.barrister2c.data.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE.
 */
public class Favorite {

    public static final String TYPE_BARRISTER = "favorite.type.barrister";

    /** Not-null value. */
    private String id;//如果是律师，就是律师id
    private String type;//收藏类型
    private String title;
    private String desc;
    private String url;//如果是收藏的其他东西
    private String thumb;//如果律师就是律师头像 ,如果是收藏的其他（如学习中心）就是缩略图 TBD
    private String addTime;//添加收藏的时间；

    public Favorite() {
    }

    public Favorite(String id) {
        this.id = id;
    }

    public Favorite(String id, String title, String thumb, String type, String desc, String url, String addTime) {
        this.id = id;
        this.title = title;
        this.thumb = thumb;
        this.type = type;
        this.desc = desc;
        this.url = url;
        this.addTime = addTime;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getAddTime() {
        return addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

}
