package com.lsm.barrister2c.data.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE.
 */
public class Favorite {

    /** Not-null value. */
    private String id;
    private String name;
    private String userIcon;

    public Favorite() {
    }

    public Favorite(String id) {
        this.id = id;
    }

    public Favorite(String id, String name, String userIcon) {
        this.id = id;
        this.name = name;
        this.userIcon = userIcon;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUserIcon() {
        return userIcon;
    }

    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon;
    }

}
